// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWtpKuF9zvz1n4WlyKYeu6T5D6-IknbI',
    appId: '1:673046838343:web:4e4de77a9d39f693da8562',
    messagingSenderId: '673046838343',
    projectId: 'pokedexstore-883b6',
    authDomain: 'pokedexstore-883b6.firebaseapp.com',
    storageBucket: 'pokedexstore-883b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVoZLG7ex9_8lBOF2-UN8G0J66HWifIU',
    appId: '1:673046838343:android:b6454265e3b3494eda8562',
    messagingSenderId: '673046838343',
    projectId: 'pokedexstore-883b6',
    storageBucket: 'pokedexstore-883b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4cghDdVDdm4-LHRsncWed_Dz0UwzeC0',
    appId: '1:673046838343:ios:9d25d4fb06773494da8562',
    messagingSenderId: '673046838343',
    projectId: 'pokedexstore-883b6',
    storageBucket: 'pokedexstore-883b6.appspot.com',
    iosClientId: '673046838343-q3hc3o4lqfhrfhbp9lfegu2mohommf0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex',
  );
}
